### ISSUE TITLE
Cannot read private messages

### ISSUE THREAD

**Issue by cyisfor** [ssbc/patchfoo#6]
Selecting /private immediately kills the server for me, with:
```
...patchfoo/lib/app.js:643
  if (this.sbot.private.read) return this.filter(this.sbot.private, opts, {})

TypeError: Cannot read property 'read' of undefined
    at App.streamPrivate (patchfoo/lib/app.js:643:24)
    at Serve.private (patchfoo/lib/serve.js:476:14)
    at Serve.path (patchfoo/lib/serve.js:347:41)
    at Serve.handle (patchfoo/lib/serve.js:307:26)
    at next (patchfoo/lib/serve.js:174:12)
    at gotData (patchfoo/lib/serve.js:159:10)
    at Serve.go (patchfoo/lib/serve.js:147:5)
    at Server.<anonymous> (patchfoo/lib/app.js:77:31)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
```

**Comment by cyisfor** [comment]
This is another README thing, I think, and also should be a more explanatory error message, saying: "Please run `sbot plugins.install ssb-private` and plugins.enable too to enable private messages." Or... selecting /private could simply trigger the installation of that plugin.
