### ISSUE TITLE
npm error ECONNREFUSED

### ISSUE THREAD

**Issue by todrobbins** [ssbc/patchfoo#7]
I'm running into this error when I get to this installation step (`npm install --registry=http://localhost:8043/`):

```
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:8043/pull-defer failed, reason: connect ECONNREFUSED 127.0.0.1:8043
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:182:13)
npm ERR!     at Socket.socketErrorListener (_http_client.js:399:9)
npm ERR!     at Socket.emit (events.js:182:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:82:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR!     at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR!  { FetchError: request to http://localhost:8043/pull-defer failed, reason: connect ECONNREFUSED 127.0.0.1:8043
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:182:13)
npm ERR!     at Socket.socketErrorListener (_http_client.js:399:9)
npm ERR!     at Socket.emit (events.js:182:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:82:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR!     at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR!   message:
npm ERR!    'request to http://localhost:8043/pull-defer failed, reason: connect ECONNREFUSED 127.0.0.1:8043',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack:
npm ERR!    'FetchError: request to http://localhost:8043/pull-defer failed, reason: connect ECONNREFUSED 127.0.0.1:8043\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketErrorListener (_http_client.js:399:9)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process.internalTickCallback (internal/process/next_tick.js:72:19)',
npm ERR!   parent: 'patchfoo' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/todrobbins/.npm/_logs/2018-11-21T21_26_33_671Z-debug.log
```

I'm not sure what to do at this point. Let me know if you want the complete log.

**Comment by Musickiller** [comment]
Is it still an issue? Coz it seem to tell you that there is problem with your ssb-npm-registry, not with patchfoo.

**Comment by stampf** [comment]
Hi, I just tried it myself, and got the same result, although I was using Patchwork.
I had ssb-server installed globally previously (I have a symbolic link in my /usr/local/bin/sbot to it), and  when I ru "sbot server", the npm registry does start, and then npm install works by connecting to the registry on localhost:8043.

**Comment by mixmix** [comment]
This repo has been deprecated. @todrobbins @clehner @noffle would one of you like to move this to git-ssb?

**Comment by hackergrrl** [comment]
@todrobbins are you still experiencing this issue?  (mix: gauging if we can just close it or not)

**Comment by todrobbins** [comment]
Sorry all! I was a bit off the radar. We can move this issue to git-ssb. I'm getting a different error now that's related to a plugin.
